name: News Event Trigger

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 mins
#  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
          PUSHOVER_USER_KEYS: ${{ secrets.PUSHOVER_USER_KEYS }}
        run: uv run -m src.main
